version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - med_expert_postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /usr/src/med_expert/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/med_expert
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  med_expert_postgres_data:
